mod.id = "fletched"
mod.name = "Fletched!"
mod.group = "com.github.pigsteel"
mod.version = "0.1.0-alpha"
mod.channel_tag = ""
mod.description = "Several new bow types, balance changes to archery, use of the fletching table, and several new arrow types. Tipped arrows are amended."
mod.authors = ["pigsteel"]
mod.contributors = []
mod.inception_year = "2026"
mod.license.name = "MIT"
mod.license.url = "https://opensource.org/licenses/MIT"
mod.license.dist = "repo"
mod.sources_url = "https://github.com/pigsteel/Fletched"
mod.homepage_url = "https://modrinth.com/mod/fletched"
mod.issues_url = "https://github.com/pigsteel/Fletched/issues"
mod.discord_url = "https://discord.gg/ZECxBsZ9x7"
[[mod.pom.developers]]
id = "pigsteel"
name = "pigsteel"
url = "https://github.com/pigsteel"

[fabric]
# https://fabricmc.net/develop/
deps.fabric-loader = "0.19.3"

[fabric."1.21.1"]
deps.minecraft = "1.21.1"
deps.fabric-api = "0.116.7+1.21.1"
deps.modmenu = "15.0.0"

[fabric."26.1.2"]
deps.minecraft = "26.1.2"
deps.fabric-api = "0.146.1+26.1.2"
deps.modmenu = "18.0.0"
publish.additionalVersions = ["26.1.1", "26.1"]

[fabric."26.2"]
deps.minecraft = "26.2"
deps.fabric-api = "0.154.2+26.2"
deps.modmenu = "20.0.1"
publish.additionalVersions = ["26.1.1", "26.1"]

[neoforge]
# https://projects.neoforged.net/

[neoforge."1.21.1"]
deps.minecraft = "1.21.1"
deps.neoforge = "21.1.235"

[neoforge."26.1.2"]
deps.minecraft = "26.1.2"
deps.neoforge = "26.1.2.78"
publish.additionalVersions = ["26.1.1", "26.1"]

[neoforge."26.2"]
deps.minecraft = "26.1.2"
deps.neoforge = "26.2.0.11-beta"
